name: pizzapp
description: Pizzeria escolar con Flutter y Supabase.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.12.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.18.0
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  url_launcher: ^6.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
